# Generated by Django 5.0.3 on 2024-04-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('execution_time', models.DateTimeField(verbose_name='time to do')),
                ('action', models.TextField(verbose_name='action')),
                ('is_pleasant', models.BooleanField(verbose_name='is pleasant')),
                ('periodic', models.PositiveSmallIntegerField(default=1, verbose_name='periodic')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='time for action')),
                ('is_public', models.BooleanField(verbose_name='is public')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.award', verbose_name='award')),
                ('parent_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='parent habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
