# Generated by Django 5.0.3 on 2024-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('execution_time', models.DateTimeField(verbose_name='time to do')),
                ('action', models.TextField(verbose_name='action')),
                ('is_pleasant', models.BooleanField(verbose_name='is pleasant')),
                ('periodic', models.PositiveSmallIntegerField(default=1, verbose_name='periodic')),
                ('time_to_complete', models.DateTimeField(verbose_name='time for action')),
                ('is_public', models.BooleanField(verbose_name='is public')),
            ],
        ),
    ]
