# Generated by Django 5.0.3 on 2024-04-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.TimeField(verbose_name='time to do'),
        ),
    ]
